#:schema node_modules/@deco/workers-runtime/config-schema.json
name = "github-projects"
main = "server/main.ts"
compatibility_date = "2025-06-17"
compatibility_flags = [ "nodejs_compat" ]
scope = "deco"

[assets]
directory = "./dist/client"
binding = "ASSETS"
not_found_handling = "single-page-application"
run_worker_first = true

[deco]
workspace = "deco"
enable_workflows = true
local = false

[deco.integration]
description = "AI-powered GitHub Projects V2 and Issues management. Automate your GitHub workflow with intelligent task management, issue tracking, and project organization through MCP tools."
friendlyName = "GitHub Projects Manager"
icon = "https://github.githubassets.com/images/modules/logos_page/GitHub-Mark.png"

[[deco.bindings]]
name = "AI_GATEWAY"
type = "mcp"
integration_name = "@deco/ai-gateway"

[[deco.bindings]]
name = "DATABASE"
type = "mcp"
integration_name = "@deco/database"
